In [1]:
import pandas as pd
import numpy as np
import torch
df = pd.read_csv('data3.csv')

df.head()

Unnamed: 0  data
0           0     0
1           1     0
2           2     2
3           3     2
4           4     0

In [35]:
sec = list(df['data'])
text = ''.join(map(str, sec))
vocab = ['0', '1', '2', '3']
vocab_size = len(set(sec))

In [28]:
text

'002201012200122002010101120122210010010101011101221211101200000022210011101100211101200020000200011011221002000110100000200121011201211001022000000031010210002200110010110010100101000122001101110000120112202110010210021111011220101001110111012011000000122100001112110100002200012100101102102000010000222110002000112010000110100100102121102001201021000201001000002132110003020201001210012012021111010110101010001003020111201011210100001000011000023110010010010210211201010013200202221010100111110210011101101110222010000110221110122001001202201001101000000121101300010121100222110000111010112200012220201110200120110210020101121210000003120101002220100002211111100000211002020010101102001010201012011000122120002122102201021210101120110020010230101000110100011200110020000121200000200020010220102200120202101200000211022020001120020011101010112211200011210120110220021200010110001200021010201010110000010110010200110100220011110010010201000222001110020202130100102203000001111020112020001011102112000

In [36]:
sec

[0,
 0,
 2,
 2,
 0,
 1,
 0,
 1,
 2,
 2,
 0,
 0,
 1,
 2,
 2,
 0,
 0,
 2,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 2,
 0,
 1,
 2,
 2,
 2,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 2,
 2,
 1,
 0,
 0,
 2,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 2,
 0,
 0,
 1,
 2,
 1,
 0,
 1,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 0,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 1,
 0,
 1,
 0,
 2,
 1,
 0,
 0,
 0,
 2,
 2,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 2,
 2,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 2,
 0,
 1,
 1,
 2,
 2,
 0,
 2,
 1,
 1,
 0,
 0,
 1,
 0,
 2,
 1,
 0,
 0,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 2,
 2,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 2,
 0,
 1,
 1,
 0,
 0,
 0,
 0,


In [37]:
vocab_size

4

In [38]:
vocab

['0', '1', '2', '3']

In [39]:
stoi = { ch:i for i,ch in enumerate(vocab) }
itos = { i:ch for i,ch in enumerate(vocab) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("00112211"))
print(decode(encode("00112211")))

[0, 0, 1, 1, 2, 2, 1, 1]
00112211


In [40]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([132080]) torch.int64
tensor([0, 0, 2, 2, 0, 1, 0, 1, 2, 2, 0, 0, 1, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0, 1,
        1, 2, 0, 1, 2, 2, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
        2, 2, 1, 2, 1, 1, 1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 0, 1, 1,
        1, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0,
        0, 1, 1, 0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        2, 0, 0, 1, 2, 1, 0, 1, 1, 2, 0, 1, 2, 1, 1, 0, 0, 1, 0, 2, 2, 0, 0, 0,
        0, 0, 0, 0, 3, 1, 0, 1, 0, 2, 1, 0, 0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 1, 0,
        1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 2, 2, 0, 0, 1, 1, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 2, 0, 1, 1, 2, 2, 0, 2, 1, 1, 0, 0, 1, 0, 2, 1, 0,
        0, 2, 1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
        0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 2, 1, 0, 0, 0, 0, 1, 1, 1, 2,
        1, 1, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 1, 1, 0, 2,
       

In [41]:
n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

In [42]:
block_size = 8
train_data[:block_size + 1]

tensor([0, 0, 2, 2, 0, 1, 0, 1, 2])

In [43]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([0]) the target: 0
when input is tensor([0, 0]) the target: 2
when input is tensor([0, 0, 2]) the target: 2
when input is tensor([0, 0, 2, 2]) the target: 0
when input is tensor([0, 0, 2, 2, 0]) the target: 1
when input is tensor([0, 0, 2, 2, 0, 1]) the target: 0
when input is tensor([0, 0, 2, 2, 0, 1, 0]) the target: 1
when input is tensor([0, 0, 2, 2, 0, 1, 0, 1]) the target: 2


In [52]:
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

In [58]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x,y = x.to(DEVICE), y.to(DEVICE)
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[0, 1, 0, 3, 2, 1, 0, 0],
        [0, 2, 1, 0, 0, 2, 1, 0],
        [0, 0, 2, 0, 0, 1, 1, 1],
        [2, 2, 0, 2, 1, 0, 0, 0]], device='cuda:0')
targets:
torch.Size([4, 8])
tensor([[1, 0, 3, 2, 1, 0, 0, 1],
        [2, 1, 0, 0, 2, 1, 0, 2],
        [0, 2, 0, 0, 1, 1, 1, 1],
        [2, 0, 2, 1, 0, 0, 0, 1]], device='cuda:0')
----
when input is [0] the target: 1
when input is [0, 1] the target: 0
when input is [0, 1, 0] the target: 3
when input is [0, 1, 0, 3] the target: 2
when input is [0, 1, 0, 3, 2] the target: 1
when input is [0, 1, 0, 3, 2, 1] the target: 0
when input is [0, 1, 0, 3, 2, 1, 0] the target: 0
when input is [0, 1, 0, 3, 2, 1, 0, 0] the target: 1
when input is [0] the target: 2
when input is [0, 2] the target: 1
when input is [0, 2, 1] the target: 0
when input is [0, 2, 1, 0] the target: 0
when input is [0, 2, 1, 0, 0] the target: 2
when input is [0, 2, 1, 0, 0, 2] the target: 1
when input is [0, 2, 1, 0, 0, 2, 1] the target: 0
when 

In [47]:
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1338)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx


m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([32, 4])
tensor(1.7783, grad_fn=<NllLossBackward0>)
01313131312103131003012311031031031032310312130031313133231012010313102011320311311201010031110320313


simplest baseline

In [48]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [55]:
batch_size = 32
for steps in range(10000): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')


    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

1.0915497541427612


In [57]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=300)[0].tolist()))

0001010202120010101200101021202110001010121202010222202021002100010010020210010320201100101010312110002030010212200021001020000100002010031020100100110020020000100200201000002201000211010020221121011000001211101210011001000212022210000100020000210000020000002020102010002000000002000101001211000020000


In [17]:
from nanogpt import GPTLanguageModel

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

import torch
import pandas as pd
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 32 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 300
n_embd = 32
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

model = GPTLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

NameError: name 'encode' is not defined

In [18]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

NameError: name 'train_data' is not defined